version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: "host"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /mnt/jellyfinMedia:/media
      - /mnt/jellyfinMedia:/media2:ro
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com

volumes:
  jellyfin-config:
  jellyfin-cache:
